version: '3.8'  #specifies docker compose version
services:
  app:
    container_name: 'app'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 5435:5435
    stdin_open: true
    environment:
      - PORT=5435
    command: npm start
  
volumes:
  node_modules: